### ISSUE TITLE
Mudar a foto de fundo 

### ISSUE THREAD

**Issue by GabrielSantosC** [PlugueHub/pluguehub.github.io#1]
Adicionar um filtro e embaçar a imagem de fundo da capa do site, para esconder o que estava acontecendo (na foto). 

Pois assim vamos conseguir focar mais na Logo da Pluguem, amo vocês

**Comment by MatheusAvellar** [comment]
Done! 😄

**Comment by GabrielSantosC** [comment]
Preciso que vocês coloquem a imagem do Plugue com .png só com o Plugue branco, sem o fundo com aquele quadrado preto, blz?
